name: On Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  wagon:
    strategy:
      matrix:
        container:
        - 'debian:latest'
        - 'ubuntu:latest'
        - 'centos:latest'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: python3 -m pip install wagon
      - name: Wagonify
        run: python3 -m wagon create . -r requirements.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with: "*.wgn"
