name: On Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  wagon:
    strategy:
      matrix:
        container:
        - 'debian:latest'
        - 'ubuntu:latest'
        - 'centos:latest'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        run: (apt-get update && apt-get install -y python3) || (yum update && dnf install -y python3)
      - name: Install
        run: python -m pip install wagon
      - name: Wagonify
        run: python -m wagon create . -r requirements.txt
      - name: Find wagon
        run: echo "WAGON=$(find *.wgn -printf "%f\n")" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with: ${{ env.WAGON }}
